name: jawara_pintar
description: Mobile application for Jawara Pintar system.

version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  image_picker: ^1.1.1  
  cupertino_icons: ^1.0.5
  google_fonts: ^4.0.4
  go_router: ^16.2.4
  intl: ^0.17.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1

flutter:
  uses-material-design: true

  assets:
    - assets/images/